//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSurvey.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BmsSurvey.Application.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active to must be after active from!.
        /// </summary>
        public static string ACTIVE_TO_GREATER_THAN_ACTIVE_FROM {
            get {
                return ResourceManager.GetString("ACTIVE_TO_GREATER_THAN_ACTIVE_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete your account!.
        /// </summary>
        public static string CANNOT_ERASE_YOUR_SELF {
            get {
                return ResourceManager.GetString("CANNOT_ERASE_YOUR_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The daily limit of overtime hours exceeded!\r\nMaximal available hours is {ComparisonValue}!.
        /// </summary>
        public static string DAILY_LIMIT_ЕXCEEDED {
            get {
                return ResourceManager.GetString("DAILY_LIMIT_ЕXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department not found!.
        /// </summary>
        public static string DEPARTMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("DEPARTMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed operation!.
        /// </summary>
        public static string FAILED_CREATE_STATEMENT {
            get {
                return ResourceManager.GetString("FAILED_CREATE_STATEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; must be greater than {ComparisonValue}!.
        /// </summary>
        public static string GREATER_THAN {
            get {
                return ResourceManager.GetString("GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format &apos;{PropertyValue}&apos;!.
        /// </summary>
        public static string INVALID_EMAIL {
            get {
                return ResourceManager.GetString("INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record not found!.
        /// </summary>
        public static string RECORD_NOT_FOUND {
            get {
                return ResourceManager.GetString("RECORD_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{PropertyName}&apos; is required field!.
        /// </summary>
        public static string REQUIRED {
            get {
                return ResourceManager.GetString("REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Employer Id must be 5 digit long!.
        /// </summary>
        public static string TABNUMBER_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("TABNUMBER_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Employer Id required!.
        /// </summary>
        public static string TABNUMBER_REQUIRED {
            get {
                return ResourceManager.GetString("TABNUMBER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user not found!.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
    }
}
