//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BmsSurvey.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LayoutResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LayoutResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BmsSurvey.WebApp.Resources.LayoutResource", typeof(LayoutResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string _2FA {
            get {
                return ResourceManager.GetString("2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add authenticator app.
        /// </summary>
        public static string _2FA_AUTHENTICATION_ADD_AUTHENTICATOR_APP {
            get {
                return ResourceManager.GetString("2FA_AUTHENTICATION_ADD_AUTHENTICATOR_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator app.
        /// </summary>
        public static string _2FA_AUTHENTICATION_ADD_RESET_APP {
            get {
                return ResourceManager.GetString("2FA_AUTHENTICATION_ADD_RESET_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup authenticator app.
        /// </summary>
        public static string _2FA_AUTHENTICATION_ADD_SETUP_APP {
            get {
                return ResourceManager.GetString("2FA_AUTHENTICATION_ADD_SETUP_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication (2FA).
        /// </summary>
        public static string _2FA_AUTHENTICATION_TITLE {
            get {
                return ResourceManager.GetString("2FA_AUTHENTICATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} recovery codes left..
        /// </summary>
        public static string _2FA_N_CODES_LEFT {
            get {
                return ResourceManager.GetString("2FA_N_CODES_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should generate a new set of recovery codes..
        /// </summary>
        public static string _2FA_N_CODES_LEFT_TEXT {
            get {
                return ResourceManager.GetString("2FA_N_CODES_LEFT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no recovery codes left..
        /// </summary>
        public static string _2FA_NO_CODES_LEFT {
            get {
                return ResourceManager.GetString("2FA_NO_CODES_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must generate a new set of recovery codes before you can log in with a recovery code..
        /// </summary>
        public static string _2FA_NO_CODES_LEFT_TEXT {
            get {
                return ResourceManager.GetString("2FA_NO_CODES_LEFT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 1 recovery code left..
        /// </summary>
        public static string _2FA_ONE_CODES_LEFT {
            get {
                return ResourceManager.GetString("2FA_ONE_CODES_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can generate a new set of recovery codes..
        /// </summary>
        public static string _2FA_ONE_CODES_LEFT_TEXT {
            get {
                return ResourceManager.GetString("2FA_ONE_CODES_LEFT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current browser has been forgotten. When you login again from this browser you will be prompted for your 2fa code..
        /// </summary>
        public static string _2FA_STATUS_BROWSER_FORGET {
            get {
                return ResourceManager.GetString("2FA_STATUS_BROWSER_FORGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this resource..
        /// </summary>
        public static string ACCESS_DENIED_TEXT {
            get {
                return ResourceManager.GetString("ACCESS_DENIED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log  in.
        /// </summary>
        public static string ACCOUNT_LOGIN {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have access to your authenticator device? You can.
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA_NO_AUTHENTICATOR_DEVICE {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA_NO_AUTHENTICATOR_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log in with a recovery code.
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA_RECOVERY_CODE_TEXT {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA_RECOVERY_CODE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember this machine.
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA_REMEMBER_MC {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA_REMEMBER_MC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login is protected with an authenticator app. Enter your authenticator code below..
        /// </summary>
        public static string ACCOUNT_LOGIN_2FA_TEXT {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_2FA_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator code.
        /// </summary>
        public static string ACCOUNT_LOGIN_AUTHENTICATOR_CODE {
            get {
                return ResourceManager.GetString("ACCOUNT_LOGIN_AUTHENTICATOR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no external authentication services configured. See this article https://go.microsoft.com/fwlink/?LinkID=532715 for details on setting up this ASP.NET application to support logging in via external services..
        /// </summary>
        public static string ACCOUNT_NO_EXTERNAL_LOGINS {
            get {
                return ResourceManager.GetString("ACCOUNT_NO_EXTERNAL_LOGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code.
        /// </summary>
        public static string ACCOUNT_RECOVERY_CODE {
            get {
                return ResourceManager.GetString("ACCOUNT_RECOVERY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code required.
        /// </summary>
        public static string ACCOUNT_RECOVERY_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("ACCOUNT_RECOVERY_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery code verification.
        /// </summary>
        public static string ACCOUNT_RECOVERY_CODE_VERIFICATION {
            get {
                return ResourceManager.GetString("ACCOUNT_RECOVERY_CODE_VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have requested to log in with a recovery code. This login will not be remembered until you provide an authenticator app code at log in or disable 2FA and log in again..
        /// </summary>
        public static string ACCOUNT_RECOVERY_CODE_VERIFICATION_TEXT {
            get {
                return ResourceManager.GetString("ACCOUNT_RECOVERY_CODE_VERIFICATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string ACCOUNT_USE_ANOTHER_SERVICE_LOG_IN {
            get {
                return ResourceManager.GetString("ACCOUNT_USE_ANOTHER_SERVICE_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string ACCOUNT_USE_LOCAL_ACCOUNT_TO_LOG_IN {
            get {
                return ResourceManager.GetString("ACCOUNT_USE_LOCAL_ACCOUNT_TO_LOG_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active From.
        /// </summary>
        public static string ACTIVE_FROM {
            get {
                return ResourceManager.GetString("ACTIVE_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active To.
        /// </summary>
        public static string ACTIVE_TO {
            get {
                return ResourceManager.GetString("ACTIVE_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string ADMINISTRATION {
            get {
                return ResourceManager.GetString("ADMINISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Administration.
        /// </summary>
        public static string ADMINISTRATION_ROLES_ADMINISTRATION {
            get {
                return ResourceManager.GetString("ADMINISTRATION_ROLES_ADMINISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Administration.
        /// </summary>
        public static string ADMINISTRATION_USERS_ADMINISTRATION {
            get {
                return ResourceManager.GetString("ADMINISTRATION_USERS_ADMINISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string AND {
            get {
                return ResourceManager.GetString("AND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator app.
        /// </summary>
        public static string AUTHENTICATOR_APP {
            get {
                return ResourceManager.GetString("AUTHENTICATOR_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete your account!.
        /// </summary>
        public static string CANNOT_ERASE_YOUR_SELF {
            get {
                return ResourceManager.GetString("CANNOT_ERASE_YOUR_SELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string CHANGE_PASSWORD {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string CHANGE_PASSWORD_STATUS {
            get {
                return ResourceManager.GetString("CHANGE_PASSWORD_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure authenticator app.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a two-factor authenticator app like Microsoft Authenticator for.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_DOWNLOAD_TEXT {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_DOWNLOAD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Authenticator for.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_GOOGLE_TEXT {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_GOOGLE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable QR code generation please read our.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have scanned the QR code or input the key above, your two factor authentication app will provide you with a unique code. Enter the code in the confirmation box below..
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT_DETAILS {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documentation.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT_LINK {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN_ALERT_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR Code or enter this key.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN1 {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to into your two factor authenticator app. Spaces and casing do not matter..
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_SCAN2 {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_SCAN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use an authenticator app go through the following steps:.
        /// </summary>
        public static string CONFIGURE_AUTHENTICATOR_APP_STEPS {
            get {
                return ResourceManager.GetString("CONFIGURE_AUTHENTICATOR_APP_STEPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm using of cookies!.
        /// </summary>
        public static string CONFIRM_COOKIES {
            get {
                return ResourceManager.GetString("CONFIRM_COOKIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string CONFIRM_EMAIL {
            get {
                return ResourceManager.GetString("CONFIRM_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email..
        /// </summary>
        public static string CONFIRM_EMAIL_TEXT {
            get {
                return ResourceManager.GetString("CONFIRM_EMAIL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string CONFIRM_PASSWORD {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string CONFIRM_PASSWORD_NOT_MATCHING {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD_NOT_MATCHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your email.
        /// </summary>
        public static string CONFIRM_YOUR_EMAIL {
            get {
                return ResourceManager.GetString("CONFIRM_YOUR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by &lt;a href=&apos;{0}&apos;&gt;clicking here&lt;/a&gt;..
        /// </summary>
        public static string CONFIRM_YOUR_EMAIL_TEXT {
            get {
                return ResourceManager.GetString("CONFIRM_YOUR_EMAIL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string CREATE_A_NEW_ACCOUNT {
            get {
                return ResourceManager.GetString("CREATE_A_NEW_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created from.
        /// </summary>
        public static string CREATE_FROM {
            get {
                return ResourceManager.GetString("CREATE_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create statement.
        /// </summary>
        public static string CREATE_STATEMENT {
            get {
                return ResourceManager.GetString("CREATE_STATEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create survey.
        /// </summary>
        public static string CREATE_SURVEY {
            get {
                return ResourceManager.GetString("CREATE_SURVEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string CULTURE {
            get {
                return ResourceManager.GetString("CULTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password required.
        /// </summary>
        public static string CURRENT_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Personal Data.
        /// </summary>
        public static string DELETE_PERSONAL_DATA {
            get {
                return ResourceManager.GetString("DELETE_PERSONAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data and close my account.
        /// </summary>
        public static string DELETE_PERSONAL_DATA_AND_CLOSE {
            get {
                return ResourceManager.GetString("DELETE_PERSONAL_DATA_AND_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string DELETE_PERSONAL_DATA_TEXT {
            get {
                return ResourceManager.GetString("DELETE_PERSONAL_DATA_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string DEPARTMENT {
            get {
                return ResourceManager.GetString("DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department management.
        /// </summary>
        public static string DEPARTMENT_MANAGEMENT {
            get {
                return ResourceManager.GetString("DEPARTMENT_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The department required.
        /// </summary>
        public static string DEPARTMENTID_REQUIRED {
            get {
                return ResourceManager.GetString("DEPARTMENTID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCTIPTION {
            get {
                return ResourceManager.GetString("DESCTIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable two-factor authentication (2FA).
        /// </summary>
        public static string DISABLE_2FA {
            get {
                return ResourceManager.GetString("DISABLE_2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        public static string DISABLE_2FA_BUTTON {
            get {
                return ResourceManager.GetString("DISABLE_2FA_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2fa has been disabled. You can reenable 2fa when you setup an authenticator app.
        /// </summary>
        public static string DISABLE_2FA_STATUS {
            get {
                return ResourceManager.GetString("DISABLE_2FA_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling 2FA does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should.
        /// </summary>
        public static string DISABLE_2FA_TEXT_DETAILS {
            get {
                return ResourceManager.GetString("DISABLE_2FA_TEXT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset your authenticator keys..
        /// </summary>
        public static string DISABLE_2FA_TEXT_DETAILS_LINK {
            get {
                return ResourceManager.GetString("DISABLE_2FA_TEXT_DETAILS_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action only disables 2FA..
        /// </summary>
        public static string DISABLE_2FA_TEXT_HEADER {
            get {
                return ResourceManager.GetString("DISABLE_2FA_TEXT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Number.
        /// </summary>
        public static string DISPLAY_NUMBER {
            get {
                return ResourceManager.GetString("DISPLAY_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        public static string DIVISION {
            get {
                return ResourceManager.GetString("DIVISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division management.
        /// </summary>
        public static string DIVISION_MANAGEMENT {
            get {
                return ResourceManager.GetString("DIVISION_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divisions.
        /// </summary>
        public static string DIVISIONS {
            get {
                return ResourceManager.GetString("DIVISIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DOWNLOAD {
            get {
                return ResourceManager.GetString("DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Your Data.
        /// </summary>
        public static string DOWNLOAD_YOUR_DATA {
            get {
                return ResourceManager.GetString("DOWNLOAD_YOUR_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid Email.
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU WANT TO GIVE US A PROPOSAL?
        ///Leave us a valid email and our employee
        ///will contact you.
        /// </summary>
        public static string EMAIL_PLEASE {
            get {
                return ResourceManager.GetString("EMAIL_PLEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email required.
        /// </summary>
        public static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email!.
        /// </summary>
        public static string ENTER_EMAIL {
            get {
                return ResourceManager.GetString("ENTER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your {0} account.
        /// </summary>
        public static string EXTERNAL_LOGIN_ASSOCIATE_ACCOUNT {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGIN_ASSOCIATE_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with {0}. Please enter an email address for this site below and click the Register button to finish logging in..
        /// </summary>
        public static string EXTERNAL_LOGIN_TEXT {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGIN_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External logins.
        /// </summary>
        public static string EXTERNAL_LOGINS {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Logins.
        /// </summary>
        public static string EXTERNAL_LOGINS_REGISTERED_LOGIN {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGINS_REGISTERED_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string EXTERNAL_LOGINS_TITLE {
            get {
                return ResourceManager.GetString("EXTERNAL_LOGINS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error from external provider: {0}.
        /// </summary>
        public static string EXTERNAL_PROVIDER_ERROR {
            get {
                return ResourceManager.GetString("EXTERNAL_PROVIDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading external login information during confirmation..
        /// </summary>
        public static string EXTERNAL_PROVIDER_ERROR_CONFIRMATION {
            get {
                return ResourceManager.GetString("EXTERNAL_PROVIDER_ERROR_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading external login information..
        /// </summary>
        public static string EXTERNAL_PROVIDER_ERROR_INFO {
            get {
                return ResourceManager.GetString("EXTERNAL_PROVIDER_ERROR_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed!.
        /// </summary>
        public static string FAILED_OPERATION {
            get {
                return ResourceManager.GetString("FAILED_OPERATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FIRSTNAME {
            get {
                return ResourceManager.GetString("FIRSTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string FIRSTNAME_REQUIRED {
            get {
                return ResourceManager.GetString("FIRSTNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For excluding.
        /// </summary>
        public static string FOR_EXCLUDING {
            get {
                return ResourceManager.GetString("FOR_EXCLUDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For including.
        /// </summary>
        public static string FOR_INCLUDING {
            get {
                return ResourceManager.GetString("FOR_INCLUDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for the survey.
        /// </summary>
        public static string FOR_THE_SURVEY {
            get {
                return ResourceManager.GetString("FOR_THE_SURVEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget this browser.
        /// </summary>
        public static string FORGET_THIS_BROWSER {
            get {
                return ResourceManager.GetString("FORGET_THIS_BROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password confirmation.
        /// </summary>
        public static string FORGOT_PASSWORD_CONFIRMATION {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string FORGOT_PASSWORD_CONFIRMATION_TEXT {
            get {
                return ResourceManager.GetString("FORGOT_PASSWORD_CONFIRMATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password.
        /// </summary>
        public static string FORGOT_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("FORGOT_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string FORGOT_YOUR_PASSWORD_ENTER_EMAIL {
            get {
                return ResourceManager.GetString("FORGOT_YOUR_PASSWORD_ENTER_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string FULLNAME {
            get {
                return ResourceManager.GetString("FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string GENERATE {
            get {
                return ResourceManager.GetString("GENERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate two-factor authentication (2FA) recovery codes.
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you lose your device and don&apos;t have the recovery codes you will lose access to your account..
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES_INFO_LOSE {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES_INFO_LOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put these codes in a safe place..
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES_SAFE_PLACE {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES_SAFE_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating new recovery codes does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should.
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES_TEXT {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset your authenticator keys..
        /// </summary>
        public static string GENERATE_2FA_RECOVERY_CODES_TEXT_LINK {
            get {
                return ResourceManager.GetString("GENERATE_2FA_RECOVERY_CODES_TEXT_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Recovery Codes.
        /// </summary>
        public static string GENERATE_RECOVERY_CODES {
            get {
                return ResourceManager.GetString("GENERATE_RECOVERY_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string HELLO {
            get {
                return ResourceManager.GetString("HELLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident.
        /// </summary>
        public static string INCIDENT {
            get {
                return ResourceManager.GetString("INCIDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not correct.
        /// </summary>
        public static string INCORRECT_PASSWORD {
            get {
                return ResourceManager.GetString("INCORRECT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authenticator code..
        /// </summary>
        public static string INVALID_AUTHENTICATOR_CODE {
            get {
                return ResourceManager.GetString("INVALID_AUTHENTICATOR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        public static string INVALID_LOGIN_ATTEMPT {
            get {
                return ResourceManager.GetString("INVALID_LOGIN_ATTEMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recovery code entered..
        /// </summary>
        public static string INVALID_RECOVERY_CODE {
            get {
                return ResourceManager.GetString("INVALID_RECOVERY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is invalid..
        /// </summary>
        public static string INVALID_VERFICATION_CODE {
            get {
                return ResourceManager.GetString("INVALID_VERFICATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string IS_ACTIVE {
            get {
                return ResourceManager.GetString("IS_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified from.
        /// </summary>
        public static string LAST_MODIFIED_FROM {
            get {
                return ResourceManager.GetString("LAST_MODIFIED_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified on.
        /// </summary>
        public static string LAST_MODIFIED_ON {
            get {
                return ResourceManager.GetString("LAST_MODIFIED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familly.
        /// </summary>
        public static string LASTNAME {
            get {
                return ResourceManager.GetString("LASTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familly is required.
        /// </summary>
        public static string LASTNAME_REQUIRED {
            get {
                return ResourceManager.GetString("LASTNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string LOCK {
            get {
                return ResourceManager.GetString("LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string LOCKED_OUT {
            get {
                return ResourceManager.GetString("LOCKED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string LOCKED_OUT_TEXT {
            get {
                return ResourceManager.GetString("LOCKED_OUT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged out of the application..
        /// </summary>
        public static string LOGOUT_TEXT {
            get {
                return ResourceManager.GetString("LOGOUT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string MANAGE_CAHNGE_ACCOUNT_SETTINGS {
            get {
                return ResourceManager.GetString("MANAGE_CAHNGE_ACCOUNT_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string MANAGE_YOUR_ACCOUNT {
            get {
                return ResourceManager.GetString("MANAGE_YOUR_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string MONTH {
            get {
                return ResourceManager.GetString("MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly overtime report.
        /// </summary>
        public static string MONTHLY_OVERTIME_REPORT {
            get {
                return ResourceManager.GetString("MONTHLY_OVERTIME_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name required.
        /// </summary>
        public static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NEW_PASSWORD {
            get {
                return ResourceManager.GetString("NEW_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password required.
        /// </summary>
        public static string NEW_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("NEW_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NEXTPAGE {
            get {
                return ResourceManager.GetString("NEXTPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nomenclatures management.
        /// </summary>
        public static string NOM_MANAGEMENT {
            get {
                return ResourceManager.GetString("NOM_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string OR {
            get {
                return ResourceManager.GetString("OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчети за извънреден труд.
        /// </summary>
        public static string OVERTIME_REPORTS {
            get {
                return ResourceManager.GetString("OVERTIME_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Statements.
        /// </summary>
        public static string OVERTIME_SRATEMENTS {
            get {
                return ResourceManager.GetString("OVERTIME_SRATEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report for overtime statements of.
        /// </summary>
        public static string OVERTIME_SRATEMENTS_REPORT {
            get {
                return ResourceManager.GetString("OVERTIME_SRATEMENTS_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string PAGE_SIZE {
            get {
                return ResourceManager.GetString("PAGE_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        public static string PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        public static string PERSONAL_DATA {
            get {
                return ResourceManager.GetString("PERSONAL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        public static string PERSONAL_DATA_DELETEINFO {
            get {
                return ResourceManager.GetString("PERSONAL_DATA_DELETEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account contains personal data that you have given us. This page allows you to download or delete that data..
        /// </summary>
        public static string PERSONAL_DATA_INFO {
            get {
                return ResourceManager.GetString("PERSONAL_DATA_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PHONE_NUMBER {
            get {
                return ResourceManager.GetString("PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PREVIOUSPAGE {
            get {
                return ResourceManager.GetString("PREVIOUSPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string PROFILE {
            get {
                return ResourceManager.GetString("PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string PROJECT {
            get {
                return ResourceManager.GetString("PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Type.
        /// </summary>
        public static string QUESTION_TYPE {
            get {
                return ResourceManager.GetString("QUESTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string QUESTIONS {
            get {
                return ResourceManager.GetString("QUESTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string REFRESH {
            get {
                return ResourceManager.GetString("REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a new user.
        /// </summary>
        public static string REGISTER_AS_NEW_USER {
            get {
                return ResourceManager.GetString("REGISTER_AS_NEW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string REMEMBER_ME {
            get {
                return ResourceManager.GetString("REMEMBER_ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string REMOVE {
            get {
                return ResourceManager.GetString("REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reques.
        /// </summary>
        public static string REQUEST {
            get {
                return ResourceManager.GetString("REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date required!.
        /// </summary>
        public static string REQUIRED_StatementDate {
            get {
                return ResourceManager.GetString("REQUIRED_StatementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours required!.
        /// </summary>
        public static string REQUIRED_StatementHours {
            get {
                return ResourceManager.GetString("REQUIRED_StatementHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket number required!.
        /// </summary>
        public static string REQUIRED_TicketNumber {
            get {
                return ResourceManager.GetString("REQUIRED_TicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket type required!.
        /// </summary>
        public static string REQUIRED_TicketType {
            get {
                return ResourceManager.GetString("REQUIRED_TicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string RESET {
            get {
                return ResourceManager.GetString("RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you reset your authenticator key your authenticator app will not work until you reconfigure it..
        /// </summary>
        public static string RESET_AUTHENTICATOR_INFO {
            get {
                return ResourceManager.GetString("RESET_AUTHENTICATOR_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator key.
        /// </summary>
        public static string RESET_AUTHENTICATOR_KEY {
            get {
                return ResourceManager.GetString("RESET_AUTHENTICATOR_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authenticator app key has been reset, you will need to configure your authenticator app using the new key..
        /// </summary>
        public static string RESET_AUTHENTICATOR_STATUS {
            get {
                return ResourceManager.GetString("RESET_AUTHENTICATOR_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process disables 2FA until you verify your authenticator app. If you do not complete your authenticator app configuration you may lose access to your account..
        /// </summary>
        public static string RESET_AUTHENTICATOR_TEXT {
            get {
                return ResourceManager.GetString("RESET_AUTHENTICATOR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string RESET_PASSWORD {
            get {
                return ResourceManager.GetString("RESET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string RESET_PASSWORD_CONFIRMATION {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here to log in.
        /// </summary>
        public static string RESET_PASSWORD_CONFIRMATION_CLICK_HERE {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRMATION_CLICK_HERE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string RESET_PASSWORD_CONFIRMATION_TEXT1 {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_CONFIRMATION_TEXT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by &lt;a href=&apos;{0}&apos;&gt;clicking here&lt;/a&gt;..
        /// </summary>
        public static string RESET_PASSWORD_EMAIL_TEXT {
            get {
                return ResourceManager.GetString("RESET_PASSWORD_EMAIL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset recovery codes.
        /// </summary>
        public static string RESET_RECOVERY_CODES {
            get {
                return ResourceManager.GetString("RESET_RECOVERY_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string RESET_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("RESET_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string ROLES {
            get {
                return ResourceManager.GetString("ROLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a department....
        /// </summary>
        public static string SELECT_DEPARTMENT {
            get {
                return ResourceManager.GetString("SELECT_DEPARTMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a division....
        /// </summary>
        public static string SELECT_DIVISION {
            get {
                return ResourceManager.GetString("SELECT_DIVISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ticket type....
        /// </summary>
        public static string SELECT_TICKET_TYPE {
            get {
                return ResourceManager.GetString("SELECT_TICKET_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification email.
        /// </summary>
        public static string SEND_VERIFICATION_EMAIL {
            get {
                return ResourceManager.GetString("SEND_VERIFICATION_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string SET_PASSWORD {
            get {
                return ResourceManager.GetString("SET_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string SET_PASSWORD_STATUS {
            get {
                return ResourceManager.GetString("SET_PASSWORD_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local account so you can log in without an external login..
        /// </summary>
        public static string SET_PASSWORD_TEXT {
            get {
                return ResourceManager.GetString("SET_PASSWORD_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your password.
        /// </summary>
        public static string SET_YOUR_PASSWORD {
            get {
                return ResourceManager.GetString("SET_YOUR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        public static string SHORTNAME {
            get {
                return ResourceManager.GetString("SHORTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The short name required.
        /// </summary>
        public static string SHORTNAME_REQUIRED {
            get {
                return ResourceManager.GetString("SHORTNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sirname.
        /// </summary>
        public static string SIRNAME {
            get {
                return ResourceManager.GetString("SIRNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sirname is required.
        /// </summary>
        public static string SIRNAME_REQUIRED {
            get {
                return ResourceManager.GetString("SIRNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string STATEMENT_DATE {
            get {
                return ResourceManager.GetString("STATEMENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string STATEMENT_HOURS {
            get {
                return ResourceManager.GetString("STATEMENT_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was added..
        /// </summary>
        public static string STATUS_EXTERNAL_LOGIN_ADDED {
            get {
                return ResourceManager.GetString("STATUS_EXTERNAL_LOGIN_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string STATUS_EXTERNAL_LOGIN_REMOVED {
            get {
                return ResourceManager.GetString("STATUS_EXTERNAL_LOGIN_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have generated new recovery codes..
        /// </summary>
        public static string STATUS_GENERATE_CODES {
            get {
                return ResourceManager.GetString("STATUS_GENERATE_CODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile has been updated.
        /// </summary>
        public static string STATUS_PROFILE_UPDATED {
            get {
                return ResourceManager.GetString("STATUS_PROFILE_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification email sent. Please check your email..
        /// </summary>
        public static string STATUS_UPDATE_PROFILE_EMAIL_SEND {
            get {
                return ResourceManager.GetString("STATUS_UPDATE_PROFILE_EMAIL_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SUBMIT {
            get {
                return ResourceManager.GetString("SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfull operation.
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string SUM {
            get {
                return ResourceManager.GetString("SUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survay management.
        /// </summary>
        public static string SURVEY_MANAGEMENT {
            get {
                return ResourceManager.GetString("SURVEY_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questuions management.
        /// </summary>
        public static string SURVEY_QUESTION_MANAGEMENT {
            get {
                return ResourceManager.GetString("SURVEY_QUESTION_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        public static string SURVEYS {
            get {
                return ResourceManager.GetString("SURVEYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer Id.
        /// </summary>
        public static string TABNUMBER {
            get {
                return ResourceManager.GetString("TABNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Employer Id required!.
        /// </summary>
        public static string TABNUMBER_REQUIRED {
            get {
                return ResourceManager.GetString("TABNUMBER_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TEXT {
            get {
                return ResourceManager.GetString("TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You!.
        /// </summary>
        public static string THANK_YOU {
            get {
                return ResourceManager.GetString("THANK_YOU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string The__0__must_be_at_least__2__and_at_max__1__characters_long_ {
            get {
                return ResourceManager.GetString("The {0} must be at least {2} and at max {1} characters long.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of property &quot;{0}&quot;  must be between {1} and {2}.
        /// </summary>
        public static string The_value_of_property___0____must_be_between__1__and__2_ {
            get {
                return ResourceManager.GetString("The value of property \"{0}\"  must be between {1} and {2}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket number.
        /// </summary>
        public static string TICKETNUMBER {
            get {
                return ResourceManager.GetString("TICKETNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket type.
        /// </summary>
        public static string TICKETTYPE {
            get {
                return ResourceManager.GetString("TICKETTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor code is required.
        /// </summary>
        public static string TWOFACTORCODE_REQUIRED {
            get {
                return ResourceManager.GetString("TWOFACTORCODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string UNLOCK {
            get {
                return ResourceManager.GetString("UNLOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string UPDATE_PASSWORD {
            get {
                return ResourceManager.GetString("UPDATE_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load user with ID &apos;{0}&apos;..
        /// </summary>
        public static string USER_NOTFOUND {
            get {
                return ResourceManager.GetString("USER_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string USERINROLE {
            get {
                return ResourceManager.GetString("USERINROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code.
        /// </summary>
        public static string VERIFICATION_CODE {
            get {
                return ResourceManager.GetString("VERIFICATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is required.
        /// </summary>
        public static string VERIFICATION_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("VERIFICATION_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string VERIFY {
            get {
                return ResourceManager.GetString("VERIFY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your oppinion matters!.
        /// </summary>
        public static string YOUR_OPINION_MATTERS {
            get {
                return ResourceManager.GetString("YOUR_OPINION_MATTERS", resourceCulture);
            }
        }
    }
}
